# Generated by Django 5.0.8 on 2025-01-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0012_subscriber_beehiiv_id_subscriber_sync_error_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='beehiiv_id',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='sync_error',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='synced_to_beehiiv',
        ),
    ]
