# Generated by Django 5.0.8 on 2024-10-05 10:15

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='articles', to='research.author'),
        ),
    ]
