# Generated by Django 5.0.8 on 2024-10-08 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.author')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
