# Generated by Django 5.0.8 on 2024-10-10 03:10

from django.db import migrations, models
from django.utils.text import slugify
from django.db import migrations

def generate_slugs(apps, schema_editor):
    Category = apps.get_model('research', 'Category')
    for category in Category.objects.all():
        category.slug = slugify(category.name)
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
