# Generated by Django 5.0.8 on 2024-10-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_remove_article_authors_articleauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='articles', through='research.ArticleAuthor', to='research.author'),
        ),
    ]
