# Generated by Django 5.0.8 on 2024-10-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_alter_article_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='table_of_contents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
