# Generated by Django 5.0.8 on 2024-10-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_article_table_of_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='sponsor_color',
            field=models.CharField(default='#FF0420', max_length=7),
        ),
        migrations.AddField(
            model_name='article',
            name='sponsor_text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
