# Generated by Django 5.0.8 on 2024-10-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_alter_article_sponsor_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sponsor_color',
            field=models.CharField(default='bg-red-700 !important', max_length=7),
        ),
        migrations.AlterField(
            model_name='article',
            name='sponsor_text_color',
            field=models.CharField(default='#bg-gray-700 !important', max_length=7),
        ),
    ]
