# Generated by Django 5.0.8 on 2024-10-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_alter_article_sponsor_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sponsor_padding',
            field=models.CharField(default='px-4 py-6', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='sponsor_color',
            field=models.CharField(default='#FF0420', max_length=7),
        ),
        migrations.AlterField(
            model_name='article',
            name='sponsor_text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
