# Generated by Django 5.0.8 on 2024-10-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_article_sponsor_padding_alter_article_sponsor_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sponsor_padding',
        ),
    ]
