# Generated by Django 5.0.8 on 2024-11-24 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_remove_article_sponsor_padding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSlugHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old_slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='research.article')),
            ],
            options={
                'db_table': 'research_articleslughistory',
                'indexes': [models.Index(fields=['old_slug'], name='research_ar_old_slu_12bba6_idx')],
                'unique_together': {('article', 'old_slug')},
            },
        ),
    ]
