# Generated by Django 5.0.8 on 2024-12-12 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_alter_article_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_article', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='related_from',
                    to='research.article',
                )),
                ('to_article', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='related_to',
                    to='research.article',
                )),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(
                blank=True,
                related_name='referenced_by',
                through='research.RelatedArticle',
                to='research.article',
            ),
        ),
        migrations.AddConstraint(
            model_name='relatedarticle',
            constraint=models.CheckConstraint(
                check=~models.Q(from_article=models.F('to_article')),
                name='prevent_self_reference',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='relatedarticle',
            unique_together={('from_article', 'to_article')},
        ),
    ]
