# Generated by Django 5.0.8 on 2024-12-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_alter_article_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, help_text='Select up to 3 related articles', related_name='referenced_by', to='research.article', verbose_name='Related Articles'),
        ),
    ]
