# Generated by Django 5.0.8 on 2024-08-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_alter_article_options_article_acknowledgement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_read',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
