# Generated by Django 5.0.8 on 2024-12-11 13:08

from django.db import migrations, models

def remove_duplicate_slugs(apps, schema_editor):
    Category = apps.get_model('research', 'Category')
    seen_slugs = {}
    
    for category in Category.objects.order_by('id'):
        base_slug = category.slug
        counter = 1
        while category.slug in seen_slugs:
            category.slug = f"{base_slug}-{counter}"
            counter += 1
        seen_slugs[category.slug] = True
        category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_relatedarticle_article_related_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
