# Generated by Django 5.0.8 on 2024-12-11 13:08

from django.db import migrations, models

def remove_duplicate_slugs(apps, schema_editor):
    Category = apps.get_model('research', 'Category')
    duplicate_slugs = Category.objects.values('slug').annotate(count=models.Count('slug')).filter(count__gt=1)
    for slug in duplicate_slugs:
        Category.objects.filter(slug=slug['slug']).exclude(id=models.Min('id')).delete()
        
class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_relatedarticle_article_related_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
