# Generated by Django 5.0.8 on 2024-12-14 11:13

import apps.research.models.article
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_article_related_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=cloudinary.models.CloudinaryField(blank=True, default=apps.research.models.article.get_default_thumb, max_length=255, verbose_name='image'),
        ),
    ]
