# Generated by Django 5.0.8 on 2025-01-21 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0018_alter_article_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_articles', to='research.category'),
        ),
    ]
