# Generated by Django 5.0.8 on 2024-09-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0018_alter_article_acknowledgement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready')], db_index=True, default='draft', max_length=10),
        ),
    ]
