# Generated by Django 5.0.8 on 2025-01-21 08:52

from django.db import migrations

def fix_primary_categories(apps, schema_editor):
    """
    Data migration to fix invalid primary_category values and set primary_category for articles without one.
    """
    Article = apps.get_model('research', 'Article')
    
    # Fix invalid primary_category values
    for article in Article.objects.all():
        if article.primary_category and not article.categories.filter(id=article.primary_category.id).exists():
            article.primary_category = None
            article.save()
    
    # Set primary_category for articles without one
    for article in Article.objects.filter(primary_category__isnull=True).exclude(categories__isnull=True):
        article.primary_category = article.categories.first()
        article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('research', '0019_article_primary_category'),
    ]

    operations = [
        migrations.RunPython(fix_primary_categories),
    ]
