# Generated by Django 5.0.8 on 2025-01-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0020_auto_20250121_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='primary_category',
        ),
        migrations.AddField(
            model_name='category',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
