name: Merge to Main

on:
  pull_request:
    branches:
      - main

jobs:
  check_source_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run checks
        run: |
          echo "This workflow runs for PR merge to the main branch."